Feature:  Add the functionality of toggling favorite product by clicking button.
matwjablonski/wdp-2304-02 pull request #11
Opened 2023-04-14 19:38 UTC by iMdPd

1) I added new functionality of toggling product favorite value,  
2) I manually set the favorite key of the first product to true,
3) After using react-redux hook (useDispatch) I had to make some changes in Jest tests of ProductBox.
I had to wrapped Product box in Provider. 
4) Button changes it's background-color on orange for favorite products. 

Link to Jira task:
https://projects.kodilla.com/browse/WDP230402-11

2023-04-16 06:13 UTC, walldy-0 approved these changes

2023-04-16 15:27 UTC, matwjablonski requested changes

2023-04-16 15:27 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          {[1, 2, 3, 4, 5].map(i => (
nie podoba mi się ta tablica tutaj, wolałbym że było to zrobione bardziej programowalnie, np:


```js
Array.from({length: 10}, (_, i) => i + 1)
```
lub
```js
[...Array(10).keys()]
```

2023-04-16 15:27 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +                <FontAwesomeIcon icon={faStar}>{i} stars</FontAwesomeIcon>
```jsx
<FontAwesomeIcon icon={i <= stars ? faStar : farStar}>{i} stars</FontAwesomeIcon>

2023-04-16 16:06 UTC, iMdPd commented on src/components/common/ProductBox/ProductBox.js
> +          {[1, 2, 3, 4, 5].map(i => (
Nie jest to kod związany z ticketem. Moje zmiany nie dotyczyły diva z klasą stars

2023-04-16 16:06 UTC, iMdPd commented on src/components/common/ProductBox/ProductBox.js
> +                <FontAwesomeIcon icon={faStar}>{i} stars</FontAwesomeIcon>
jw. Zmiany nie dotyczą treści zadania.

2023-04-17 10:18 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          {[1, 2, 3, 4, 5].map(i => (
ale zostało to przez Ciebie zmienione, a zatem możesz to przy okazji poprawić

2023-04-17 15:14 UTC, stanleyoos approved these changes

2023-04-19 10:09 UTC, merged