Fix start command
matwjablonski/wdp-2304-02 pull request #12
Opened 2023-04-16 07:41 UTC by walldy-0

2023-04-16 14:31 UTC, matwjablonski approved these changes

2023-04-17 11:27 UTC, Evil-Cloud89 approved these changes

2023-04-17 12:26 UTC, ElizaHynek requested changes
U mnie  te zmiany powodują, że strona się nie odpala:
![image](https://user-images.githubusercontent.com/116754359/232483536-66fe9285-c998-41f1-a890-07696730221f.png)

2023-04-17 15:58 UTC, stanleyoos approved these changes

2023-04-17 17:54 UTC, walldy-0 commented
> U mnie te zmiany powodują, że strona się nie odpala

A jaką masz wersję node?

2023-04-17 19:30 UTC, iMdPd commented
> 
Najnowszą

2023-04-17 19:34 UTC, ElizaHynek commented
Ja mam chyba 14 - specjalnie przeinstalowalam wg zaleceń mojego Mentora, żeby przypadkiem nie było problemów w projekcie.
Najnowsza wersja mi sypała różnymi błędami..

2023-04-17 19:58 UTC, walldy-0 commented
Ja mam 18.12.1

Zadajcie proszę komendę: 'node --version' i prześlijcie wynik


W dniu 17.04.2023 o 21:34, elisskka pisze:
>
> Ja mam chyba 14 - specjalnie przeinstalowalam wg zaleceń mojego 
> Mentora, żeby przypadkiem nie było problemów w projekcie.
> Najnowsza wersja mi sypała różnymi błędami..
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/matwjablonski/wdp-2304-02/pull/12#issuecomment-1511971015>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/A4PBEMRFGACAIHROBBL6AS3XBWLMLANCNFSM6AAAAAAW76IY4Q>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2023-04-18 16:23 UTC, iMdPd approved these changes

2023-04-19 20:45 UTC, ElizaHynek requested changes
U mnie nadal nie działa przy wersji 18 noda, działa natomiast ze zmienioną kolejnością. 
"start:react": "react-scripts start --openssl-legacy-provider"
Sprawdźmy proszę wszyscy i taką zmianę proponuję.

2023-04-20 13:31 UTC, matwjablonski commented
powinniście zdecydować wspólnie na jedną wersję node'a - nie musi to być najnowsza.

2023-04-21 05:36 UTC, closed without merging