WDP230402-14 Add responsiveness main menu and searchbox
matwjablonski/wdp-2304-02 pull request #15
Opened 2023-04-16 13:05 UTC by stanleyoos

Póki co wygląd zmienia się tylko dla wymagań tabletu, prośba o pomoc w jaki sposób mógłbym stworzyć 

"a mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony. "

https://projects.kodilla.com/browse/WDP230402-14

2023-04-16 14:50 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> -  :global(.container) > :global(.row) {
sprawdziłeś czy usunięcie tego stylu nie rozwali czegoś? ten styl jest w globalnym kontekście, więc był używany prawdopodobnie w bardzo wielu miejscach

2023-04-17 13:54 UTC, ElizaHynek reviewed
Ja bym spróbowała dodać ikonę menu i zrobić wybór opcji w dropdown przez ul>li>ul>li podobnie jak w [WDP230402-10] i ustawić display: none, a na hoverze display: block.
Może w ten sposób..? :)

2023-04-17 15:21 UTC, stanleyoos commented on src/components/layout/MenuBar/MenuBar.module.scss
> -  :global(.container) > :global(.row) {
Sprawdziłem i wydaje mi się że nie popsuło to niczego, nie wiem czy jest sens na sztywno ustawiać wysokość tego div'a (w tym przypadku nav'a)

2023-04-18 22:01 UTC, iMdPd commented on src/components/layout/MenuBar/MenuBar.module.scss
> -  :global(.container) > :global(.row) {
> Sprawdziłem i wydaje mi się że nie popsuło to niczego, nie wiem czy jest sens na sztywno ustawiać wysokość tego div'a (w tym przypadku nav'a)

We wszystkich js'ach z listy poniżej występuje ten sam schemat .root{
.container > row }

Nie ryzykowałbym z usuwaniem globalnych styli. 

<img width="429" alt="Zrzut ekranu 2023-04-19 o 00 00 00" src="https://user-images.githubusercontent.com/117603283/232914678-b5101936-a451-4156-94a0-58eb693df6cc.png">

2023-04-19 13:25 UTC, Evil-Cloud89 requested changes

2023-04-19 13:25 UTC, Evil-Cloud89 commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  position: absolute;
Usuń tę linijkę, dzięki temu lista będzie dobrze położona na stronie w pełnym wymiarze i w mobilnym.

2023-04-19 13:25 UTC, Evil-Cloud89 commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  left:-60px;
left też nie będzie potrzebne. Dodaj zamiast tego text-align: center; by lepiej wyglądało rozwijane menu.

2023-04-20 09:17 UTC, stanleyoos commented
Teraz pojawia się problem rozwiniętego menu które rozciąga cały div z MenuBar

2023-04-20 20:16 UTC, ElizaHynek requested changes
może widziałeś - Mariusz proponował stylowanie menu w innym tasku 10 - może to pomoże..?

2023-04-20 22:08 UTC, iMdPd commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  background-color: #f1f1f1;
Definiuj kolory w pliku settings za pomocą globalnych nazw `$` a następnie używaj ich w stylach komponentów

2023-04-22 19:34 UTC, ElizaHynek commented
dla tabletów - ikona menu ok, ale dropdown rozwala Ci style 
![image](https://user-images.githubusercontent.com/116754359/233803175-58a6f90b-ccb4-41f2-bece-6b9320a41ee0.png)

dla mobilek nadal brak stylowania

2023-04-23 12:23 UTC, iMdPd requested changes
Wprowadź proszę zmiany jak w uwagach i rozwiąż konflikty

2023-04-23 17:18 UTC, iMdPd requested changes
To co Ci napisałem w prywatnej wiadomości, przy rozdzielczości <470px powinieneś pomyśleć o innym układzie.

2023-04-26 08:54 UTC, ElizaHynek requested changes
nadal brak stylowania dla mobile

2023-04-26 13:04 UTC, stanleyoos commented
Sprawdźcie jak teraz to wygląda, nie zmieniałem już ułożenia poszczególnych elementów a jedynie pozmieniałem ich szerokości na mniejszych ekranach

2023-04-26 16:09 UTC, iMdPd reviewed
Na 320px dalej chowają się za viewportem. Rozwiąż konflikty i dam Approve, żeby nie męczyć

2023-04-28 11:08 UTC, ElizaHynek approved these changes

2023-04-28 19:44 UTC, iMdPd approved these changes

2023-04-28 22:06 UTC, merged