Feature/wdp230402 10 dropdown menu
matwjablonski/wdp-2304-02 pull request #18
Opened 2023-04-17 08:48 UTC by Evil-Cloud89

Dodałem dropdown menu w sekcji search zamieniając aktualny element select.

Link do JIRA: https://projects.kodilla.com/browse/WDP230402-10

2023-04-17 21:23 UTC, iMdPd commented on src/components/features/ProductSearch/ProductSearch.js
> +            <li>Coming soon</li>
Wpisujesz kategorie na sztywno. Nie lepiej użyć kategorii z redux store?

2023-04-17 21:25 UTC, iMdPd commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      }
Dodaj background-color na hover li. 
Poświęć trochę czasu na style, bo jak narazie to masz białe tło i prawy border 1px

2023-04-17 22:24 UTC, Evil-Cloud89 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      }
Dzięki za info o border, miało być całe a wyszło tylko z prawej.

2023-04-18 05:58 UTC, stanleyoos commented
Działa dobrze ale wydaje mi się że przydałaby się lekka zmiana background-color na hover

2023-04-18 21:48 UTC, iMdPd commented
> Działa dobrze ale wydaje mi się że przydałaby się lekka zmiana background-color na hover

Jestem tego samego zdania co Stanleyoos. Użyj jakiegoś jasno-szarego koloru na hover.

2023-04-18 21:49 UTC, iMdPd commented
>

2023-04-20 17:31 UTC, iMdPd requested changes
A co powiesz na takie rozwiązanie? : 

![Nagranie z ekranu 2023-04-20 o 19 25 28](https://user-images.githubusercontent.com/117603283/233442689-80b8d522-0cdc-429b-9eec-3d2b3c431d17.gif)

Ikona powinna mieć w takim przypadku:
className={"mx-2"}
border: 1px solid;
border-left: none;
padding 9.5px  

<ul>: 
position: absolute, 
top: 40px;
right: 30 albo 35px

Na koniec doszlifuj media dla mobilek i będzie złoto. 
Reszta wygląda kozacko.

2023-04-20 17:47 UTC, Evil-Cloud89 commented
RWD nie jest częścią tego zadania - to chyba task nr 14. Style mogę zmienić bo faktycznie prezentują się bardzo dobrze. Jednak uważam, że RWD powinno być dokonane przez osobę robiącą task 14 by uniknąć konfliktów.

2023-04-20 18:31 UTC, iMdPd commented
> 

Zwracam honor.

2023-04-20 18:31 UTC, iMdPd approved these changes

2023-04-21 08:51 UTC, iMdPd approved these changes

2023-04-21 09:46 UTC, walldy-0 approved these changes

2023-04-21 13:55 UTC, matwjablonski requested changes

2023-04-21 13:55 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +          background-color: white; // docelowo będzie kolor ze zmienną z pliku settings.scss
tak jak pisałem, kolor w takiej formie jest nie do przyjęcia, tym bardziej z komentarzem w języku polskim.

docelowo czyli kiedy? jest na to zadanie? jak tak to zostawisz to tak będzie już zawsze. proszę popraw ;)

2023-04-21 14:56 UTC, Evil-Cloud89 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +          background-color: white; // docelowo będzie kolor ze zmienną z pliku settings.scss
Dziękuję za przypomnienie, myślałem że to poprawiłem przy wcześniejszym commicie. Komentarz usunięty, dodane zmienne z odpowiednimi kolorami do pliku settings i tutaj by była ciągłość stylu i nazw.

2023-04-22 19:37 UTC, ElizaHynek approved these changes

2023-04-23 08:51 UTC, stanleyoos approved these changes

2023-04-23 21:31 UTC, matwjablonski approved these changes

2023-04-23 21:31 UTC, merged