Feature/wdp230402 15/rwd topbar banner
matwjablonski/wdp-2304-02 pull request #19
Opened 2023-04-17 12:02 UTC by ElizaHynek

Dodałam media query dla mobilek w dwóch rozdzielczościach.
Topbar wydaje mi się ok, ale w bannerze card jest trochę niesubordynowany :/ Czy można tu zastosować inny sposób na rozmieszczenie elementów?
link jira: https://projects.kodilla.com/browse/WDP230402-15

2023-04-17 21:44 UTC, iMdPd reviewed
TopBar rozjeżdża się na rozdzielczości 320px. Zmniejsz szerokość diva z ikonami. 
Dla CompanyClaim uzyj grida.

2023-04-18 14:03 UTC, ElizaHynek commented
Dodałam nowrap dla topbar - dla 320px jest już ok;
na CompanyClaim posterowałam flexboxem - też jest ok

2023-04-18 21:54 UTC, iMdPd requested changes
TopBar wygląda teraz zdecydowanie lepiej. Zwróć uwagę, że przy zawartości koszyka > 9 liczby zaczynają uciekać z prawej strony poza widok. 

<img width="488" alt="Zrzut ekranu 2023-04-18 o 23 51 20" src="https://user-images.githubusercontent.com/117603283/232913704-aa006a60-1499-4179-b30b-e2d7a3954168.png">

2023-04-19 19:34 UTC, ElizaHynek commented
ok, poprawione :)

2023-04-20 09:03 UTC, Evil-Cloud89 approved these changes

2023-04-20 09:03 UTC, Evil-Cloud89 commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +            <div className={styles.cartCounter}>99999</div>
Zmień na 0 tak jak było wcześniej.

2023-04-20 17:38 UTC, iMdPd reviewed
Liczba w koszyku dalej wyjeżdża poza ekran. Może użyj transform: transition(-50%, 50%)

<img width="319" alt="Zrzut ekranu 2023-04-20 o 19 33 11" src="https://user-images.githubusercontent.com/117603283/233444861-c6ff95e3-e587-4efd-ae62-8af93ec1f52b.png">

2023-04-20 22:13 UTC, iMdPd approved these changes

2023-04-20 22:14 UTC, Evil-Cloud89 commented
Jeśli dobrze pamiętam to w jednym z pierwszych tasków była mowa o limicie 99999 dla produktów. Stąd więc sprawdzamy aż do takiej liczby.

2023-04-21 05:46 UTC, merged