Set new styles for .cartCounter selector
matwjablonski/wdp-2304-02 pull request #2
Opened 2023-04-13 06:29 UTC by iMdPd

I set alternative styles for the .cartCounter selector. 
Adding `width: fit-content` would be enough. But I decided to add an additional **orange border color** and **8.5px padding** - with single numbers, border looks more rounded. 
I changed the **color** of the number - in the future it will improve the possibility of making global changes.

Two examples below:
<img width="86" alt="Zrzut ekranu 2023-04-13 o 08 22 28" src="https://user-images.githubusercontent.com/117603283/231672776-272cbfc0-233c-48d3-bb1d-bcfb7957c440.png">

<img width="98" alt="Zrzut ekranu 2023-04-13 o 08 22 52" src="https://user-images.githubusercontent.com/117603283/231672794-4ac740b2-5949-4ffa-a9ed-f8983bc5cebe.png">

2023-04-13 09:57 UTC, matwjablonski requested changes

2023-04-13 09:57 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        background-color: #363636;
proszę nie wpisuj kolorów bezpośrednio. po to mamy zmienne aby je wykorzystywać.

2023-04-13 09:57 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        color: #ffffff;
jak wyżej

2023-04-13 09:58 UTC, matwjablonski commented
w opisie poproszę jeszcze link do zadania w JIRA

2023-04-13 15:51 UTC, ElizaHynek approved these changes

2023-04-16 05:42 UTC, walldy-0 approved these changes

2023-04-16 06:08 UTC, merged