Add RWD mode in app state
matwjablonski/wdp-2304-02 pull request #20
Opened 2023-04-17 16:00 UTC by walldy-0

Ustawienie trybu wyświetlania w stanie aplikacji, w zależności od szerokości ekranu.
JIRA: https://projects.kodilla.com/browse/WDP230402-20

Dla trybów 'mobile' i 'tablet' ustawiłem ilość wyświetlanych produktów na 4, bo nie bardzo rozumiem od czego ma to zależeć...

2023-04-17 21:48 UTC, iMdPd commented on src/settings.js
> +  mobile: { name: 'mobile', minWidth: 1 },
Minimalna rozdzielczość na smartfona to  320px.

2023-04-17 21:51 UTC, iMdPd commented on src/utils/getBrowserWidth.js
> +
Dlaczego stosujesz 3 warianty odczytania szerokości strony?

2023-04-18 06:13 UTC, walldy-0 commented on src/settings.js
> +  mobile: { name: 'mobile', minWidth: 1 },
> Minimalna rozdzielczość na smartfona to 320px.

Mogę zmienić, choć niczego to nie zmieni :)

2023-04-18 06:17 UTC, walldy-0 commented on src/utils/getBrowserWidth.js
> +
> Dlaczego stosujesz 3 warianty odczytania szerokości strony?

Wsparcie dla archaicznych przeglądarek. Może rzeczywiście trochę na wyrost...

2023-04-18 08:51 UTC, iMdPd commented on src/utils/getBrowserWidth.js
> +
> > Dlaczego stosujesz 3 warianty odczytania szerokości strony?
> 
> Wsparcie dla archaicznych przeglądarek. Może rzeczywiście trochę na wyrost...

To tylko moja propozycja, aby pozostać przy jednym wariancie. Z tego co wiem to często wsparcie stosuje się do jednej max 2 wersji przeglądarek wstecz. Ale dev'em nie jestem xd

2023-04-18 08:54 UTC, iMdPd commented on src/settings.js
> +  mobile: { name: 'mobile', minWidth: 1 },
> > Minimalna rozdzielczość na smartfona to 320px.
> 
> Mogę zmienić, choć niczego to nie zmieni :)

Tylko dla czytelności, zakładamy że minimalna szerokość to 320px a nie 1-319px.  Chociaż, wydaje mi się że to Galaxy Fold ma najwęższą szerokość ekranu -  280px.

2023-04-18 10:31 UTC, walldy-0 commented on src/settings.js
> +  mobile: { name: 'mobile', minWidth: 1 },
Poprawione

2023-04-19 10:18 UTC, matwjablonski requested changes

2023-04-19 10:18 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +    let productsPerPage = 8; // default value for desktop mode
ta wartość nie musi być tej metodzie komponentu klasowego

przenieś ją do pól klasy

```jsx
class A {
  DEFAULT_PRODUCTS_PER_PAGE = 8;
  
  render() {
    this.DEFAULT_PRODUCTS_PER_PAGE = 4;
  }
}

2023-04-19 10:18 UTC, matwjablonski commented on src/utils/getBrowserWidth.js
> +
wsparcie mamy opisane w package.json - możecie sobie sprawdzić caniuse lub na stronie mdn czy nadal wymagane jest to rozróżenienie

2023-04-19 10:18 UTC, matwjablonski commented on src/utils/getViewportMode.js
> +  } else {
ten else jest tutaj zbędny ;)


możesz go pominąć

2023-04-20 13:37 UTC, matwjablonski approved these changes

2023-04-20 17:42 UTC, iMdPd commented on src/components/layout/MainLayout/MainLayout.js
> +    // initialize mode
Usuń komentarz

2023-04-20 17:42 UTC, iMdPd approved these changes

2023-04-20 19:52 UTC, ElizaHynek requested changes
hej, w rozdzielczości 991 i niżej jest po 4 produkty na stronie (w 2 lub 4 rzędach) - zgodnie z taskiem powinien być zawsze jeden rząd, czyli po 2 produkty dla 576-991px i 1 produkt <576.

2023-04-21 17:50 UTC, walldy-0 commented
> hej, w rozdzielczości 991 i niżej jest po 4 produkty na stronie (w 2 lub 4 rzędach) - zgodnie z taskiem powinien być zawsze jeden rząd, czyli po 2 produkty dla 576-991px i 1 produkt <576.

Poprawione

2023-04-22 16:30 UTC, iMdPd approved these changes

2023-04-22 16:34 UTC, iMdPd commented
> Wprowadziłem zmiany wskazane przez Elizę, rozwiązałem konflikt w MainLayout.js. Pozostaje problem z .eslintrc - dodałem zmiany, bo bez tego nie mogłem zrobić commita: eslint --fix [failed] ... Error: Failed to load parser 'babel-eslint' declared in '.eslintrc': Cannot find module 'babel-eslint'
> 
> Jak to można rozwiązać?

W głównym  branchu jest `"parser": "@babel/eslint-parser",`

2023-04-22 16:58 UTC, walldy-0 commented
> > Wprowadziłem zmiany wskazane przez Elizę, rozwiązałem konflikt w MainLayout.js. Pozostaje problem z .eslintrc - dodałem zmiany, bo bez tego nie mogłem zrobić commita: eslint --fix [failed] ... Error: Failed to load parser 'babel-eslint' declared in '.eslintrc': Cannot find module 'babel-eslint'
> > Jak to można rozwiązać?
> 
> W głównym branchu jest `"parser": "@babel/eslint-parser",`



> > Wprowadziłem zmiany wskazane przez Elizę, rozwiązałem konflikt w MainLayout.js. Pozostaje problem z .eslintrc - dodałem zmiany, bo bez tego nie mogłem zrobić commita: eslint --fix [failed] ... Error: Failed to load parser 'babel-eslint' declared in '.eslintrc': Cannot find module 'babel-eslint'
> > Jak to można rozwiązać?
> 
> W głównym branchu jest `"parser": "@babel/eslint-parser",`

Zapytam inaczej: czy z tym PR jest wszystko ok?

2023-04-22 19:44 UTC, ElizaHynek approved these changes

2023-04-23 09:12 UTC, stanleyoos commented
![image](https://user-images.githubusercontent.com/46224471/233830495-1ef260bb-13c0-46fa-b70e-58b6eb545353.png)

Miałbym małą sugestie:

1. na rozdzielczości pomiędzy 970 a 1200px produkty nie są wyśrodkowane tak jak poniżej 970px (widać to na załączonym zdjęciu)

2. nie wiem czy to treść tego zadania ale to ciągłe migotanie kategorii aktywnej, w tym przypadku Bed bardzo źle wygląda, to samo z kropkami obok, jest ich tak dużo że zakrywają pozostałe kategorie

2023-04-23 09:15 UTC, stanleyoos reviewed
![image](https://user-images.githubusercontent.com/46224471/233830841-c8fe4a35-96c2-4e32-911c-41aad42a9afd.png)


Miałbym małą sugestie:

1.  na rozdzielczości pomiędzy 970 a 1200px produkty nie są wyśrodkowane tak jak poniżej 970px (widać to na załączonym zdjęciu)

2. nie wiem czy to treść tego zadania ale to ciągłe migotanie kategorii aktywnej, w tym przypadku Bed bardzo źle wygląda, to samo z kropkami obok, jest ich tak dużo że zakrywają pozostałe kategorie

2023-04-23 12:13 UTC, Evil-Cloud89 commented
Zauważyłem, że między rozdzielczością 576 a 767 wyświetla się jeden produkt po lewej stronie oraz nagłówek jest niewidoczny.
![2023-04-23_14h08_26](https://user-images.githubusercontent.com/118907932/233839056-e0e8da95-c4d0-4c65-acaf-d57453e5f8fe.jpg)

2023-04-23 12:28 UTC, iMdPd requested changes
Faktycznie sypie się apka przy zmniejszeniu rozdzielczości

2023-04-23 18:01 UTC, walldy-0 commented
> Faktycznie sypie się apka przy zmniejszeniu rozdzielczości

Nie wiem co zrobić z tymi kropkami. Jak będzie 100 produktów, to będzie 100 kropek na mobile - bez sensu...

2023-04-25 21:34 UTC, matwjablonski commented
schowaj kropki na mobilne :)

2023-04-25 22:15 UTC, walldy-0 commented
> schowaj kropki na mobilne :) i daj strzałki < > do nawigacji :)

To jest słuszna koncepcja :) Rozważałem podobną - choć bez strzałek :)

2023-04-26 11:24 UTC, walldy-0 commented
> > schowaj kropki na mobilne :) i daj strzałki < > do nawigacji :)

Miałem problemy z przejściem na tego brancha (errory, konflikty i inne), więc taniej mi było zrobić to zadanie na nowym branchu.
Teraz pytanie: co powinienem zrobić, żeby bałaganu nie narobić?

2023-04-26 17:36 UTC, iMdPd approved these changes

2023-04-28 08:14 UTC, matwjablonski commented
@stanleyoos @Evil-Cloud89 blokujecie merge, proszę o sprawdzenie tego prą

2023-04-28 08:14 UTC, matwjablonski commented
@walldy-0 konflikty :)

2023-04-28 10:22 UTC, stanleyoos approved these changes

2023-04-28 14:44 UTC, walldy-0 commented
> @walldy-0 konflikty :)

Na tę chwilę nie ma :)

2023-04-29 13:11 UTC, Evil-Cloud89 approved these changes
Popraw konflikty i będzie ok.

2023-04-30 18:12 UTC, walldy-0 commented
> Popraw konflikty i będzie ok.

Poprawiam od czasu do czasu...
2023-40-30 20:11 - nie ma konfliktów

2023-05-01 07:27 UTC, merged