19 / FEATURE: Add animation of changing categories/pages
matwjablonski/wdp-2304-02 pull request #21
Opened 2023-04-18 20:50 UTC by iMdPd

I added chairs, sofas, tables and dinings pictures,
I changed style of naming pictures for better image source writing,
I used fade on product container after changing category or page

Link to Jira task:
https://projects.kodilla.com/browse/WDP230402-19

2023-04-20 20:30 UTC, ElizaHynek requested changes
Hej, funkcjonalność działa jeszcze niepoprawnie (choć nie wiem czy dot. tego zadania) - jak wybierzesz sobie trzecią stronę na Bed, to po wybraniu innej kategorii nie czyści stanu i dalej jest na trzeciej stronie (a np chair nie ma 3 strony).

Co do PR to nie będe mogła zatwierdzić ze względu na zmiany w package.json (które mi nie działają)

2023-04-20 22:17 UTC, iMdPd commented
> 

Nie jest to część tego zadania. Funkcjonalność dotyczyła wyłącznie dodania animacji przejścia pomiędzy kategoriami produktów oraz stronami kategorii produktów

2023-04-20 22:21 UTC, iMdPd commented
> Hej, funkcjonalność działa jeszcze niepoprawnie (choć nie wiem czy dot. tego zadania) - jak wybierzesz sobie trzecią stronę na Bed, to po wybraniu innej kategorii nie czyści stanu i dalej jest na trzeciej stronie (a np chair nie ma 3 strony).
> 
> Co do PR to nie będe mogła zatwierdzić ze względu na zmiany w package.json (które mi nie działają)

Wprowadziłem zmiany w package.json oraz configu eslintrc

2023-04-21 10:34 UTC, walldy-0 commented on src/components/features/NewFurniture/NewFurniture.js
> +            className={i === activeCategory ? styles.active : undefined}
zamień Category na Page (brak aktywnej kropki)

2023-04-21 10:51 UTC, walldy-0 commented on src/redux/productsRedux.js
A to chyba nie ten task...

2023-04-21 17:22 UTC, iMdPd commented on src/redux/productsRedux.js
Nie, miałeś rację. Dzięki, że wyłapałeś.

2023-04-21 18:59 UTC, walldy-0 commented on src/redux/productsRedux.js
A ja to ciągle widzę

2023-04-21 21:57 UTC, closed without merging