Functionality/wdp230402 21 product rating with stars
matwjablonski/wdp-2304-02 pull request #23
Opened 2023-04-19 12:14 UTC by Evil-Cloud89

Link do JIRA: https://projects.kodilla.com/browse/WDP230402-21

Wprowadziłem możliwość oceniania produktów. Można najechać na każdą gwiazdkę i zmienić jej kolor oraz można po kliknięciu ustawić swoją ocenę.

2023-04-19 15:06 UTC, iMdPd commented on .eslintrc
>    "parserOptions": {
Co ta zmiana wprowadza, jeśli można wiedzieć??

2023-04-19 15:08 UTC, iMdPd commented on src/components/common/ProductBox/ProductBox.js
> +    console.log('You gave', productId, 'rating of:', newRating, 'stars');
Czyść console.logi

2023-04-19 15:13 UTC, iMdPd commented on src/components/features/NewFurniture/NewFurniture.js
>                </div>
Zapisujesz w stanie aplikacji dodatkowy klucz userRating. Nie ma potrzeby dodawania go jako osobny argument komponentu. Spread operator {...item} zrobi brudną robotę za Ciebie.

2023-04-19 15:21 UTC, iMdPd requested changes
Ta część zadania nie została przez Ciebie spełniona: 
Przy odświeżeniu strony klient chciałby widzieć od razu "moją ocenę" w co najmniej jednym produkcie, czyli trzeba przykładowe dane wrzucić do stanu początkowego.

Deklarujesz userRating ale na stronie wyświetlany jest w formie czarnych gwiazdek zamiast żółtych. Naciśnięcie gwiazdki nie wywołuje żadnej akcji w storze. Moim zdaniem powinieneś dodać do stora klucz myRate z właściwością początkową = 0. 
Albo stworzyć akcję, która będzie dodawała taki klucz do stora z wartością gwiazdki dopiero po wychwyceniu zachowania na stronie.

2023-04-19 15:41 UTC, Evil-Cloud89 commented on .eslintrc
>    "parserOptions": {
Potrzebowałem tego by w końcu puścić commit i pushować bo miałem z tym problem.

2023-04-19 15:42 UTC, Evil-Cloud89 commented on src/components/common/ProductBox/ProductBox.js
> +    console.log('You gave', productId, 'rating of:', newRating, 'stars');
Dzięki za przypomnienie.

2023-04-19 16:02 UTC, Evil-Cloud89 commented on src/components/features/NewFurniture/NewFurniture.js
>                </div>
Dzięki za podpowiedź.

2023-04-20 17:43 UTC, iMdPd commented on .eslintrc
>    "parserOptions": {
Z tą zmianą ja nie mogę commitować zmian xDD

2023-04-20 17:48 UTC, iMdPd requested changes
Robi wrażenieee. ;d 
Brakuje mi jeszcze akcji  która spowoduje nadpisanie zmiany po dodaniu oceny/nowej oceny przez użytkownika strony. 

![Nagranie z ekranu 2023-04-20 o 19 45 22](https://user-images.githubusercontent.com/117603283/233447240-86ad6fb4-e7f0-467f-adee-b4a2da4beb24.gif)

2023-04-20 20:53 UTC, ElizaHynek requested changes
jest super - brakuje tylko nadpisania stanu, po zmianie liczby gwiazdek prze użytkownika
![image](https://user-images.githubusercontent.com/116754359/233485213-4fcb4278-e020-41b1-b4b3-6405261e7d92.png)

2023-04-21 10:41 UTC, Evil-Cloud89 commented
Teraz powinno być ok.

2023-04-21 11:15 UTC, walldy-0 commented on src/redux/productsRedux.js
> +});
Sekcje "Action types" i "Action creators" są niżej.
Zachowaj konwencję i użyj createActionName().

2023-04-21 11:26 UTC, walldy-0 commented on src/redux/initialState.js
> +      userRating: 4,
Czym się różni stars od userRating?

2023-04-21 12:21 UTC, ElizaHynek approved these changes

2023-04-21 17:35 UTC, iMdPd commented on src/redux/productsRedux.js
> +});
Dorzucam ostatnie trzy grosze : Klucz nazywa się userRating a kreator akcji UPDATE_CLIENT_RATING. 
Wprowadź zmiany jak opisał kolega wyżej i podmień nazwę na UPDATE_USER_RATING a będzie cacy.

2023-04-21 21:12 UTC, iMdPd requested changes
Ws. komentarza walld'iego, możesz wzorować się pozostałymi subreducerami

2023-04-22 05:29 UTC, Evil-Cloud89 commented on src/redux/productsRedux.js
> +});
Poprawione i zmienione.

2023-04-22 14:30 UTC, walldy-0 commented
WARNING in [eslint]
src\components\common\ProductBox\ProductBox.js
  Line 7:3:    'faStar' is defined but never used   no-unused-vars
  Line 11:20:  'farStar' is defined but never used  no-unused-vars

2023-04-22 16:59 UTC, iMdPd approved these changes
Usuń tylko nieużywane importy

2023-04-22 21:49 UTC, Evil-Cloud89 commented
Poprawione

2023-04-23 09:16 UTC, stanleyoos commented
Działa ekstra!

2023-04-23 09:16 UTC, stanleyoos approved these changes

2023-04-23 14:16 UTC, walldy-0 approved these changes

2023-04-23 14:27 UTC, walldy-0 commented on src/components/common/ProductBox/ProductBox.js
> -  faStar,
unused

2023-04-23 14:28 UTC, walldy-0 approved these changes

2023-04-23 21:36 UTC, merged