WDP230402-18: Add bootstrap classes to footer
matwjablonski/wdp-2304-02 pull request #24
Opened 2023-04-20 09:55 UTC by stanleyoos

Dodałem klasy bootstrapowe, dodatkowy pusty div powyżej breakpoint'u lg zabiera całą szerokość ponad copyright i ikonkami socjali

https://projects.kodilla.com/browse/WDP230402-18

2023-04-20 17:56 UTC, iMdPd requested changes
Podobajmu mnie się. Zostały dwie sprawy ro załatwienia: 
1) Na szerokości strony <1200px dla tekstu `all rights reserved` reserved ucieka Ci na dół a miejsca na stronie jeszcze jest sporo. 
2) Na szerokości stony <991px cały tekst i napisy ustawiają się z dołu - wyśrodkuj je proszę na divie

2023-04-23 07:57 UTC, stanleyoos commented
1. to pozostałe miejsce to o którym piszesz to pusty div który ma prawdopodobnie coś zawierać w przyszłości, ewentualnie mógłbym zmienjszyć czcionkę lub użyć <br> aby słowo Reserved tak nie zwisało

2023-04-23 12:44 UTC, Evil-Cloud89 commented
W rozdzielczości między 768 a 990 stopka i metody płatności mogłyby być bardziej wyrównane do środka. Bo obecnie to tak wygląda: 
![2023-04-23_14h40_34](https://user-images.githubusercontent.com/118907932/233840404-c36e68cd-7559-4446-baf8-fff9bf175533.jpg)

Dodatkowo w rozdzielczości poniżej 768 stopka jest w jednym długim rzędzie i metody płatności są na środku (więc tu jest ok) ale Reserved z All Rights Reserved ucieka do niższy poziom (może zmniejsz czcionkę): 
![2023-04-23_14h44_18](https://user-images.githubusercontent.com/118907932/233840553-16d7ffe9-d85b-435f-85bb-1c44ec1c76e3.jpg)

2023-04-23 12:52 UTC, iMdPd requested changes
Moim zdaniem, ten div służy wyłącznie do wycentrowania środkowego diva.
podmień kod w linijkach 100-107 i sprawdź co się stanie
```
<div className={styles.bottomBar}>
      <div className='container'>
        <div className='row  align-items-center'>
          <div className=' d-none d-lg-block col-3 text-center'></div>
          <div className={'col text-left text-lg-center ' + styles.copyright}>
            <p>©Copyright 2016 Bazar | All Rights Reserved</p>
          </div>
          <div className={'col-5 col-lg-3 text-right ' + styles.socialMedia}>
```

2023-04-23 13:09 UTC, iMdPd commented
> W rozdzielczości między 768 a 990 stopka i metody płatności mogłyby być bardziej wyrównane do środka. Bo obecnie to tak wygląda: ![2023-04-23_14h40_34](https://user-images.githubusercontent.com/118907932/233840404-c36e68cd-7559-4446-baf8-fff9bf175533.jpg)
> 
> Dodatkowo w rozdzielczości poniżej 768 stopka jest w jednym długim rzędzie i metody płatności są na środku (więc tu jest ok) ale Reserved z All Rights Reserved ucieka do niższy poziom (może zmniejsz czcionkę): ![2023-04-23_14h44_18](https://user-images.githubusercontent.com/118907932/233840553-16d7ffe9-d85b-435f-85bb-1c44ec1c76e3.jpg)

Moim 

> W rozdzielczości między 768 a 990 stopka i metody płatności mogłyby być bardziej wyrównane do środka. Bo obecnie to tak wygląda: ![2023-04-23_14h40_34](https://user-images.githubusercontent.com/118907932/233840404-c36e68cd-7559-4446-baf8-fff9bf175533.jpg)
> 
> Dodatkowo w rozdzielczości poniżej 768 stopka jest w jednym długim rzędzie i metody płatności są na środku (więc tu jest ok) ale Reserved z All Rights Reserved ucieka do niższy poziom (może zmniejsz czcionkę): ![2023-04-23_14h44_18](https://user-images.githubusercontent.com/118907932/233840553-16d7ffe9-d85b-435f-85bb-1c44ec1c76e3.jpg)

Zdjęcie z metodami płatniczymi jest childem diva orders. Na dużych rozdzielczościach contend divów jest przytulony do lewej strony a co za tym idzie i zdjęcie z metodami płatniczymi. Dopiero na małych rozdzielczościach jest ono wyśrodkowane tak jak pozostała treść divów. Moim zdaniem to jest dobre zachowanie.

2023-04-23 13:26 UTC, stanleyoos commented
Wprowadziłem zmiany o których pisaliście, sprawdźcie proszę jak teraz to wygląda

2023-04-23 17:20 UTC, iMdPd approved these changes
Jest ok!

2023-04-23 19:16 UTC, walldy-0 approved these changes

2023-04-24 11:12 UTC, ElizaHynek commented
osobiście metody płatności wyśrodokowałabym całkowicie dla tabletów, bo gteraz jest tak:
![image](https://user-images.githubusercontent.com/116754359/233980213-fd4959c6-61bb-48bf-8a5c-a99573d23c6c.png)

2023-04-26 08:51 UTC, ElizaHynek approved these changes

2023-04-26 09:57 UTC, Evil-Cloud89 approved these changes

2023-04-27 08:55 UTC, merged