Feature/wdp230402 13/add swipeable component
matwjablonski/wdp-2304-02 pull request #25
Opened 2023-04-20 15:41 UTC by walldy-0

Dodałem komponent Carousel z obsługą swipe i zastosowałem go w NewFurniture.
JIRA: https://projects.kodilla.com/browse/WDP230402-13

2023-04-20 18:28 UTC, iMdPd reviewed
Jest super! 
Jedną rzecz wychwyciłem: 
Wystarczy dodać na element karuzeli `margin 1rem`. Wtedy w trakcie wykonywania swipe, ProductBoxy nie będą ze sobą sklejone. 

![Nagranie z ekranu 2023-04-20 o 20 23 26](https://user-images.githubusercontent.com/117603283/233455479-e519470d-6aba-470e-9577-375a10a83c45.gif)

2023-04-21 17:49 UTC, iMdPd requested changes
Nie zapomnij o zmianie w package.json

2023-04-21 17:49 UTC, iMdPd commented on src/components/common/Carousel/Carousel.module.scss
> +  display: inline-block;
Dodaj  : `margin: 1rem;`

2023-04-21 19:35 UTC, walldy-0 commented on src/components/common/Carousel/Carousel.module.scss
> +  display: inline-block;
Dodałem

2023-04-21 21:09 UTC, iMdPd approved these changes

2023-04-22 19:54 UTC, ElizaHynek approved these changes

2023-04-23 12:45 UTC, Evil-Cloud89 approved these changes

2023-04-23 21:39 UTC, merged