Feature/wdp230402 22/component promoted
matwjablonski/wdp-2304-02 pull request #26
Opened 2023-04-20 20:59 UTC by ElizaHynek

Dodałam nowy komponent i 2 sekcje - 1 zmodyfikowana productBox, 2 - nowa.
Stylowanie wg sugestii klienta.
Jeszcze mam problem z zaciąganiem danych ze state - nie wiem czego mi brakuje, ale wysyłam PR - może pójdzie szybciej :)

jira: https://projects.kodilla.com/browse/WDP230402-22

2023-04-20 22:53 UTC, Evil-Cloud89 commented
Super wygląda, zostało tylko kilka szczegółów: 
- nie ma oceny produktu (wszystkie gwiazdki są białe), 
- brak starej, przekreślonej i szarej ceny,
- brak aktualnej ceny przy walucie,
- przydałby się lekki odstęp między 3 dolnymi przyciskami,
- można lekko zaokrąglić rogi przycisku SHOP NOW .

2023-04-21 18:09 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +            <button className={styles.button}>&lsaquo;</button>
Zamiast `&lsaquo;`
 <FontAwesomeIcon icon={faChevronLeft}></FontAwesomeIcon>
 tylko nie zapomnij zrobić importu

2023-04-21 18:09 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +            <button className={styles.button}>&rsaquo;</button>
Zamiast `&lsaquo;`
 <FontAwesomeIcon icon={faChevronRight></FontAwesomeIcon>
 tylko nie zapomnij zrobić importu

2023-04-21 18:17 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +                <h2>save up to 50% of all furniture</h2>
Trzymaj się konwencji, nie jest to nagłówek, nie używaj tagów h. 
Zamiast h1 i h2 użyłbym 2 x `<p>` furniture objąłbym tagiem `<span>` i dodatkowo nałożył w scss klasę na pogrubienie. Możesz wzorować się moimi pomysłami z https://github.com/matwjablonski/wdp-2304-02/pull/27

2023-04-21 18:19 UTC, iMdPd commented on src/components/features/Promoted/Promoted.module.scss
> +
Pozbądź się drugiej pustej spacji.

2023-04-21 18:19 UTC, iMdPd commented on src/components/features/Promoted/Promoted.module.scss
> +      color: #f4f5f7;
stosuj nazwy globalne kolorów zapisane w pliku settings

2023-04-21 18:25 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +const Promoted = ({ name, price, stars, oldPrice, favorite, compare }) => (
Task dotyczy pobierania danych z InitialState, a nie przekazywania propsów do komponentu z rodzica.

2023-04-21 18:28 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +                </ul>
Tu jak nic wypadało by użyć logiki podobnej do tej, która renderuje gwiazdki. Ponadto, używasz jej w linii 75.

2023-04-21 18:29 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +                ))}
Pamiętaj o robieniu pulli z maina tworząc branche. 
Lokiga w mainie uległa zmianie: 
`   {[...Array(5).keys()].map(i => (
            <a key={i} href='#'>
              <FontAwesomeIcon icon={i <= stars ? faStar : farStar}>
                {i} stars
              </FontAwesomeIcon>
            </a>
          ))}`

2023-04-21 18:39 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +
Zamiast dublować cały zapis komponentu ProductBox.js mogła byś go wywołać w tym pliku i przekazać mu dodatkowy atrybut jakim jest 3 ikona. Będziesz musiała wprowadzić dodatkową linijkę w ProductBox.js w postaci {`odebrany prop trzeciej ikony` && prop 3 ikony}. Zadziała to w taki sposób, że w NewFurniture nie przekazujesz ikony więc? W NewFurniture ona się nie pojawi. Co innego tutaj :)
Uprości to komponent i nabierze on większej czytelności. Pamiętaj, jeśli coś już zostało stworzone to szkoda Twojego czasu na tworzenie tego od nowa.

2023-04-21 18:40 UTC, iMdPd commented on src/components/features/Promoted/Promoted.module.scss
> + */
Jak wyżej, wywołaj komponent, a powtórzone style zaczną być zbędne.

2023-04-21 18:49 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +              </div>
Nie traktuj tego jako konieczność. dotyczy to linijek 53-68
Taka drobna uwaga, jak chciałabyś wskoczyć poziom wyżej z czytelnością kodu. Zwróć uwagę, że 4-krotnie powtarzasz logikę kodu`<div>h1,h2,<div>`. Jeśli coś w kodzie się powtarza, to znaczy, że można to uprościć. 
sposobów jest wiele. Takim prostym, który możesz wykorzystać to np. tablica tablic, albo tablica obiektów. 
`const array = [[25,days],...,[59,secs]]`
dalej lecisz z kodem {array.forEach((el)=> {
 <div className={styles.item}>
                <h4>el[1]</h4>
                <h5>el[2]</h5>
              </div>
})}
Osobiście zrezygnowałbym z nagłówków h4 i h5 na korzyść tagu p

2023-04-21 18:51 UTC, iMdPd requested changes
Czekam na poprawki.

2023-04-22 12:43 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +const Promoted = ({ name, price, stars, oldPrice, favorite, compare }) => (
poprawione

2023-04-22 13:03 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +            <button className={styles.button}>&lsaquo;</button>
ok, zmienione.
styl overflow: none nic nie zmienia, więc pominęłam

2023-04-22 13:44 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.module.scss
> +      color: #f4f5f7;
przed utworzeniam brancha nie było tych kolorów, więc teraz nie mogę zmienić

2023-04-22 14:04 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +                </ul>
pewnie tak, ale zadanie nie dotyczy logiki, tylko wygląda - na tę logikę wypadałoby utworzyć dodatkowe zadanie

2023-04-22 14:11 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +
proponuję na to osobne zadanie - to z taska zostało wykonane i nie powinno wstrzymywać PR

2023-04-22 14:30 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +              </div>
poprawiłam nagłówki na p

2023-04-22 14:33 UTC, ElizaHynek commented
Poprawiłam wszystkie błędy i kilka sugestii. Pozostałe kwestie proponuję rozwiązać w dodatkowym tasku, gdyż nie dotyczą bezpośrednio tego. Komponent działa poprawnie, tzn pobiera dane ze stanu i jest ostylowany.
Dodatkowo, blokujemy się z tym PR. To moja propozycja :)

2023-04-22 16:49 UTC, iMdPd commented on src/components/features/Promoted/Promoted.module.scss
> +      color: #f4f5f7;
Na branchy main jest ten kolor zapisany w pliku settings. Zrób pulla, żeby zaciągnąć wszystkie zmiany z maina.

2023-04-22 16:49 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +                </ul>
niech wypowie się PM

2023-04-23 13:33 UTC, Evil-Cloud89 approved these changes

2023-04-23 13:33 UTC, Evil-Cloud89 approved these changes

2023-04-23 14:05 UTC, walldy-0 approved these changes

2023-04-23 21:42 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +                </ul>
w opisie taska jest tylko wygląd, @ElizaHynek czy mogę Cię prosić o utworzenie zadania na funkcjonalność za 3 SP? :)

2023-04-23 21:43 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +
refaktoryzacja może być częścią PRa, zgadzam się z Mariuszem akurat tutaj ;)

2023-04-24 17:03 UTC, iMdPd commented on src/components/features/Promoted/Promoted.js
> +                </ul>
takie zadanie jest już stworzone i zakolejkowane u mnie . Obecnie czekam z rozpoczęciem tego zadania do momentu zmergowania tego PR.

2023-04-24 17:59 UTC, ElizaHynek commented on src/components/features/Promoted/Promoted.js
> +
po dodaniu ProductBox mamy taką sytuację:
![image](https://user-images.githubusercontent.com/116754359/234077811-3a0ae59d-3ff5-46ea-b64d-a4d2b526d31c.png)

W designie nie ma tych 2 buttonów, nie ma też przerwy między image a content, więc komponent jest do przebudowy. Chyba, że można tu jakieś super zabiegi zastosować, le to już nie umiem.
Na ten moment mam tak:

![image](https://user-images.githubusercontent.com/116754359/234078337-76586444-aed2-4a1c-9fb6-c42ece389bff.png)

2023-04-27 08:06 UTC, matwjablonski approved these changes

2023-04-27 08:07 UTC, merged