Add and fix styles for Select
matwjablonski/wdp-2304-02 pull request #3
Opened 2023-04-13 09:16 UTC by Evil-Cloud89

Czcionka zmniejszona do 14 px zgodnie z designem, outline zlikwidowany i dodany hover. 
Zmiana w package.json wynika ze zmiany jaką opisałem na kanale projektu aby strona się ładowała.

2023-04-13 09:52 UTC, matwjablonski approved these changes

2023-04-13 09:52 UTC, matwjablonski commented
dodaj do opisu link do zadania w JIRA

2023-04-13 14:59 UTC, ElizaHynek approved these changes

2023-04-13 17:32 UTC, walldy-0 requested changes
Do poprawki

2023-04-13 17:55 UTC, Evil-Cloud89 commented on package.json
> +    "react-scripts": "5",
Jak pisałem w komentarzu: Zmiana w package.json wynika ze zmiany jaką opisałem na kanale projektu aby strona się ładowała.

2023-04-14 17:40 UTC, Evil-Cloud89 commented
Ok, yarrn.lock i package.json usunięte.

2023-04-16 06:07 UTC, matwjablonski commented
dlaczego usunięto package.json i yarn.lock? to są pliki które powinny pozostać w kodzie

2023-04-16 06:07 UTC, matwjablonski requested changes
przywróć pliki które usunęłaś

2023-04-16 16:56 UTC, closed without merging