25 / FEATURE: Create sale section
matwjablonski/wdp-2304-02 pull request #31
Opened 2023-04-21 23:26 UTC by iMdPd

I created a fully styled sale section right above the new furniture section. All boxes have a constant height. I hope I correctly understood the part related to getting data from application state.... I've created new selector to get those products which old price is bigger than actual price. To improve UX, every time you refresh the page list of sale product will be shuffled. Products are selected from application state.  Shuffling products results in a different order of products in the array each time page is refreshed. From now Im using first three product in sale section. I used ternary operator to show percentage decrease of product price. 

Link to Jira task:
https://projects.kodilla.com/browse/WDP230402-25

2023-04-22 20:30 UTC, ElizaHynek commented on src/components/features/SaleBoxes/SaleBoxes.module.scss
> +    height: 500px;
zmniejszyłabym do 400px - będzie lepiej wizualnie wyglądało

2023-04-22 20:34 UTC, ElizaHynek requested changes

2023-04-22 20:34 UTC, ElizaHynek commented on src/components/features/SaleBoxes/SaleBoxes.module.scss
> +          margin: 0;
tutaj dodałabym większy margin od góry i pomiędzy collection i price - będzie lepiej wygładało

2023-04-23 10:49 UTC, iMdPd commented
I've changed SaleBox styles as Eliza asked. I set the styles according to the guidelines of the settings file.

2023-04-23 14:07 UTC, Evil-Cloud89 approved these changes

2023-04-23 14:46 UTC, walldy-0 commented
Na tablecie kolumna nie jest wyrównana.

![image](https://user-images.githubusercontent.com/119411250/233846541-1bedd0af-876b-41ed-81d1-2ccc36e74a92.png)

2023-04-23 14:49 UTC, walldy-0 reviewed
Na tablecie kolumna jest niewyrównana.

![image](https://user-images.githubusercontent.com/119411250/233846738-39f01c98-04f6-4245-a3ce-05b37110cc35.png)

2023-04-23 17:13 UTC, iMdPd commented
Dzięki, zmiany zostały wprowadzone.

2023-04-23 18:41 UTC, walldy-0 approved these changes

2023-04-24 15:06 UTC, merged