Add feedback components
matwjablonski/wdp-2304-02 pull request #32
Opened 2023-04-22 11:22 UTC by walldy-0

Dodałem sekcję Feedback.
JIRA: https://projects.kodilla.com/browse/WDP230402-33

2023-04-22 16:46 UTC, iMdPd approved these changes

2023-04-22 20:40 UTC, ElizaHynek approved these changes

2023-04-23 17:16 UTC, Evil-Cloud89 approved these changes

2023-04-23 21:50 UTC, matwjablonski requested changes

2023-04-23 21:50 UTC, matwjablonski commented on src/components/features/Feedbacks/Feedbacks.js
> +  for (let i = 0; i < feedbacks.length; i++) {
taką operację wykonasz przy każdym re-renderze komponentu, zdecydowanie wolałbym tutaj żebyś użył `useMemo`

2023-04-24 04:47 UTC, walldy-0 commented on src/components/features/Feedbacks/Feedbacks.js
> +  for (let i = 0; i < feedbacks.length; i++) {
Poprawiłem

2023-04-24 04:59 UTC, matwjablonski approved these changes

2023-04-24 04:59 UTC, merged