Feature/wdp230402 27 Gallery component
matwjablonski/wdp-2304-02 pull request #34
Opened 2023-04-22 22:41 UTC by Evil-Cloud89

Link do JIRA: https://projects.kodilla.com/browse/WDP230402-27

Czysty komponent ze stylami dla sekcji Galeria.

2023-04-23 10:59 UTC, iMdPd commented on src/components/layout/Gallery/Gallery.js
> +                <span className={styles.tooltip}>Add to cart</span>
To wtedy możesz usunąć.

2023-04-23 11:01 UTC, iMdPd commented on src/components/layout/Gallery/Gallery.js
> +                <FontAwesomeIcon icon={faShoppingBasket} />
Tooltip jest bootstrapowym komponentem :

`<Button variant='outline' className={styles.tooltipButton} data-toggle="tooltip" data-placement="right" title="Add to cart">`

Pod maską ma ustalony wygląd i działanie na hover. Odpadnie Ci sporo stylowania. 

https://getbootstrap.com/docs/4.0/components/tooltips/

2023-04-23 11:04 UTC, iMdPd commented on src/components/layout/Gallery/Gallery.js
> +                ></img>
Produkty powinieneś pobierać ze stanu aplikacji - to jest część zadania (a treści pobierać ze stanu aplikacji.)

2023-04-23 11:32 UTC, iMdPd commented on src/components/layout/Gallery/Gallery.js
> +              </div>
Zachowanie gwiazdek nie działa. Trzeba poczekać na merga odpowiedniego taska i wykorzystać logikę działania ratingu gwiazdek. Przydatne może okazać się wykonanie code review w pozostałych PR

2023-04-23 11:35 UTC, iMdPd requested changes
Czekamy na merge wymaganych PR aby ukończyć ten task.

2023-04-25 16:00 UTC, Evil-Cloud89 commented
A czy style w mniejszych rozdzielczościach nie należą do taska RWD?

2023-04-25 17:41 UTC, ElizaHynek commented
Wg mnie ostylowanie tego komponentu jest w tym tasku - na designie mamy podział tych sekcji na 50%,
![image](https://user-images.githubusercontent.com/116754359/234355797-7c7b44ef-818b-45ee-a5ee-512d6abcab3b.png)

a wyświetlam na laptopie i taki już nie jest. Jest inny tak, ale opisuje zmiany tylko na telefonach. Dobrze, żeby wyświetlało się poprawnie i tutaj.
Może wprowadzić tylko row i col dla sekcji?

2023-04-27 06:51 UTC, Evil-Cloud89 commented
Teraz powinno lepiej wyglądać poniżej 1200. Reszta rozdzielczości będzie w RWD.

2023-04-27 14:04 UTC, ElizaHynek approved these changes

2023-04-28 08:52 UTC, iMdPd approved these changes

2023-04-28 10:00 UTC, merged