Implementation of multilanguage support
matwjablonski/wdp-2304-02 pull request #36
Opened 2023-04-24 21:27 UTC by walldy-0

Dodałem obsługę języków i pliki z tłumaczeniami dla en i pl.
JIRA: https://projects.kodilla.com/browse/WDP230402-40

2023-04-25 06:13 UTC, matwjablonski requested changes
w zadaniu było również o dodaniu tłumaczeń. widzę że dodałeś klucze, ale trzeba je jeszcze wyświetlić na widoku

2023-04-25 06:13 UTC, matwjablonski commented on src/App.js
> +  <Suspense fallback={null}>
dlaczego ten fallback zwraca null?

2023-04-25 09:34 UTC, walldy-0 commented on src/App.js
> +  <Suspense fallback={null}>
> dlaczego ten fallback zwraca null?

Nie tworzyłem żadnego loadera, bo to raczej nie jest element zadania.
Użyłem tego, żeby wyeliminować error "Component suspended while rendering[...]" podczas zmiany języka. Zadziałało w tej postaci. Czy mam coś z tym zrobić?

2023-04-25 11:40 UTC, walldy-0 commented
> w zadaniu było również o dodaniu tłumaczeń. widzę że dodałeś klucze, ale trzeba je jeszcze wyświetlić na widoku

Mam nadzieję, że tłumaczenie nie dotyczy całej aplikacji :)

2023-04-25 11:41 UTC, matwjablonski commented
wszystkich stałych / programowalnych elementów aplikacji - z pominięciem nazw i opisów produktów

2023-04-25 11:44 UTC, matwjablonski requested changes

2023-04-25 11:44 UTC, matwjablonski commented on src/App.js
> +  <Suspense fallback={null}>
daj chociaż tekst "Trwa ładowanie" / "Loading"

2023-04-25 21:38 UTC, matwjablonski approved these changes

2023-04-26 08:59 UTC, ElizaHynek approved these changes

2023-04-26 09:32 UTC, Evil-Cloud89 approved these changes

2023-04-26 13:14 UTC, stanleyoos approved these changes

2023-04-26 16:17 UTC, merged