Feature/wdp230402 30/brands component
matwjablonski/wdp-2304-02 pull request #39
Opened 2023-04-26 15:50 UTC by stanleyoos

I created Brands component which loads all brands from initialState.
In piublic/images new folder was created with example jpgs.
All brands are maped into Brand component (placed in components/common)

2023-04-26 17:38 UTC, iMdPd commented on src/components/common/Brand/Brand.js
> +  console.log(logo);
Wyoutuj console logi

2023-04-26 17:47 UTC, iMdPd commented on src/components/layout/Brands/Brands.module.scss
> +    color: rgb(255, 255, 255);
używaj kolory zdef. w pliku settings

2023-04-26 17:47 UTC, iMdPd commented on src/components/layout/Brands/Brands.module.scss
> +    border-bottom: 1px solid rgb(182, 180, 180);
settings pliczek

2023-04-26 17:53 UTC, iMdPd commented on src/components/common/Brand/Brand.module.scss
> +}
Tu zrobiłeś trochę burdel. Apka po wyrednerowaniu posiada tagi html - img, które odnoszą się wyłącznie do zdjęć z logiem firm. Może takich zdjęć renderowanych przez stronę jest więcej? Logo firmy, sposoby płatności? 
Nigdy nie styluj w appce elementów html bo przez przypadek nadpiszesz pozostałe.

2023-04-26 17:54 UTC, iMdPd commented on src/components/common/Brand/Brand.js
> +    <div className={styles.class}>
używaj nazewnictwa lepiej określającego stylowany element.

2023-04-26 17:56 UTC, iMdPd requested changes
Dodaj większą ilość elementów brands. Na 6 elementach funkcjonalność będzie kiepsko działać.

2023-04-27 17:11 UTC, iMdPd commented on src/redux/initialState.js
> +  ],
Poprzez zwiększenie liczby marek miałem na myśli, że dodasz nowe. Wyobraź sobie sytuację w której slider jest paskiem , który obraca się na rolce. Slider zaczyna się od Marki ADIDAS. Zaczyna się przesuwać. Nagle na pozycji 7 znowu pojawia się marka ADIDAS. Na 11 znowu. Po 13 pozycji z powrotem pojawi się marka o id 1 czyli ADIDAS.

2023-04-27 17:13 UTC, iMdPd commented on src/components/layout/Brands/Brands.js
> +  faArrowCircleRight,
Gdzie wykorzystujesz ten import?

2023-04-27 17:13 UTC, iMdPd commented on src/components/layout/Brands/Brands.js
> +  faArrowCircleLeft,
Do usunięcia niewykorzystywane importy.

2023-04-27 17:15 UTC, iMdPd requested changes
Popraw proszę.

2023-04-28 10:41 UTC, stanleyoos commented on src/components/layout/Brands/Brands.js
> +  faArrowCircleLeft,
Poprawione

2023-04-28 15:17 UTC, ElizaHynek approved these changes

2023-04-28 19:45 UTC, iMdPd approved these changes

2023-04-28 22:04 UTC, merged