Fix profit links
matwjablonski/wdp-2304-02 pull request #4
Opened 2023-04-13 09:25 UTC by walldy-0

Zmiana elementów korzyści na linki z :hover-em
Link w JIRA: https://projects.kodilla.com/browse/WDP230402-3

2023-04-13 09:46 UTC, matwjablonski commented
w opisie zadania brakuje linku do zadania w JIRA

2023-04-13 09:47 UTC, matwjablonski requested changes

2023-04-13 09:47 UTC, matwjablonski commented on package.json
> +    "start:react": "react-scripts --openssl-legacy-provider start",
czy to jest część tego zadania? nie powinno być tego w tym PR

2023-04-13 09:47 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> -  &.active {
usunąłeś klasę active z css'a, a zostawiłeś logikę w pliku komponentu

2023-04-13 10:46 UTC, walldy-0 commented
Link w JIRA: https://projects.kodilla.com/browse/WDP230402-3

2023-04-16 06:06 UTC, matwjablonski commented
dlaczego ma usunąć yarn.lock?

2023-04-16 06:06 UTC, matwjablonski approved these changes

2023-04-16 07:28 UTC, iMdPd commented
Pisałem aby usunąć pliki z PR nie z projektu.

2023-04-17 11:20 UTC, iMdPd approved these changes

2023-04-17 11:23 UTC, Evil-Cloud89 approved these changes

2023-04-17 12:04 UTC, ElizaHynek approved these changes

2023-04-17 15:51 UTC, merged