WDP230402-48 refactor Promoted
matwjablonski/wdp-2304-02 pull request #42
Opened 2023-04-27 13:35 UTC by ElizaHynek

https://projects.kodilla.com/browse/WDP230402-48

poprawiłam błąd - nie zaciągały się obrazki po zmianie nazwy;
stworzyłam dodatkowy komponent, który jest wspolny dla PoductBox i Promoted

2023-04-27 13:41 UTC, matwjablonski requested changes

2023-04-27 13:41 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +  const product = useSelector(state => getOne(state, props.id));
wszystkie propsy są destrukturyzowane, id też mogłoby być ;)

2023-04-27 13:50 UTC, ElizaHynek commented
poprawione

2023-04-27 15:48 UTC, Evil-Cloud89 commented
Eslint się czepia kilku linijek ale komponent działa.
![2023-04-27_17h46_55](https://user-images.githubusercontent.com/118907932/234916269-da4b6e83-78a9-47b8-8451-1dabf760c1e1.jpg)

2023-04-27 15:49 UTC, Evil-Cloud89 approved these changes

2023-04-27 17:00 UTC, iMdPd approved these changes

2023-04-28 08:08 UTC, matwjablonski commented
@ElizaHynek poprawisz te rzeczy z lintera?

2023-04-28 09:42 UTC, ElizaHynek commented
![image](https://user-images.githubusercontent.com/116754359/235114055-47486ae1-b9f0-4ed3-8fa7-ec17b6e204c7.png)

2023-04-28 09:59 UTC, matwjablonski approved these changes

2023-04-28 09:59 UTC, merged