5 / FEATURE: Add styles for favorite and compare selectors
matwjablonski/wdp-2304-02 pull request #7
Opened 2023-04-13 21:14 UTC by iMdPd

In InitialState file, for each product I've added a new keys: favorite and compare. They can handle boolean values. 
Favorited or compared product has a colored and scaled symbol. 

Link to Jira task:
https://projects.kodilla.com/browse/WDP230402-5

2023-04-14 06:35 UTC, stanleyoos approved these changes

2023-04-14 10:37 UTC, walldy-0 requested changes
Na stronie nie widać który produkt ma aktywny atrybut. Klasy nie są przypisane w komponencie.

2023-04-14 15:18 UTC, ElizaHynek reviewed
Po otwarciu strony ma być co najmniej po jednym produkcie, który ma aktywne... - na razie nic się nie zmieniło na stronie

2023-04-14 15:27 UTC, iMdPd commented
I'm so sorry, last night I forgot to commit last file with ternary validation.... My bad.

2023-04-16 05:47 UTC, walldy-0 approved these changes

2023-04-16 06:40 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +        <Button className={favorite ? styles.favorite : ''} variant='outline'>
to można zapisać krócej wykorzystując fakt że operator && zwraca wartość ostatniego przetwarzanego wyrażenia:

```jsx
className={favorite && styles.favorite}

2023-04-16 06:41 UTC, matwjablonski commented
@ElizaHynek sprawdź proszę w kontekście swojego komentarza

@iMdPd masz konflikty :)

2023-04-17 10:14 UTC, merged