Bug/wdp230402 8 use variable for colors
matwjablonski/wdp-2304-02 pull request #9
Opened 2023-04-14 10:29 UTC by Evil-Cloud89

W pliku settings dodałem wszystkie kolory jakie były w plikach z komponentami. W przypadku dodania nowego wystarczy go dodać do innych i **prośba tak jak w komentarzu w pliku tych kolorów nie używać bezpośrednio w komponentach**.
W dalszej części utworzyłem zmienne dla wszystkich obecnych plików, jak również zastąpiłem kolory w poszczególnych plikach tymi nowymi i starymi zmiennymi, by można było zmieniać kolory w dowolny sposób korzystając tylko z jednego pliku.

2023-04-14 15:11 UTC, ElizaHynek approved these changes

2023-04-15 11:06 UTC, iMdPd commented on src/styles/settings.scss
Określając nazwy stałych, unikaj nazewnictwa określającego zastosowany kolor. Co jeśli w przyszłości będziemy musieli zdefiniować nowe kolory strony? Dziwnie by wyglądało, jakbyśmy podmienili w przyszłości kolor #d58e32 na czerwony a nazwa globalnej dalej pozostałaby orangeGold.

2023-04-15 11:07 UTC, iMdPd commented on src/styles/settings.scss
> +
Nie twórz nowych stałych dla wcześniej określonych stałych. Nie jest to dobre rozwiązanie pod kątem wydajnościowym.

2023-04-15 11:07 UTC, iMdPd requested changes

2023-04-15 11:07 UTC, iMdPd commented on src/styles/settings.scss
> +$fb-box-hover-content-small-circle-bg: $orangeGold;
Nie powtarzaj stałych.

2023-04-16 14:24 UTC, matwjablonski commented on src/styles/settings.scss
> +
nie ma to wpływu jeśli chodzi o sass'a, docelowo i tak zostanie to przeniesione do css'a, gdzie zmiennych nie będzie

2023-04-16 14:25 UTC, matwjablonski commented on src/styles/settings.scss
> +$fb-box-hover-content-small-circle-bg: $orangeGold;
jak dla mnie to podejście jest ok, zgodziłbym się z takim tworzeniem zmiennych :)

2023-04-16 14:26 UTC, matwjablonski requested changes

2023-04-16 14:26 UTC, matwjablonski commented on src/components/common/Button/Button.module.scss
> +  color: $pureWhite;
prosiłbym o zastosowanie takiej samej formy pisania zmiennych albo camelCase albo kebab-case ;)

2023-04-16 17:14 UTC, Evil-Cloud89 commented on src/components/common/Button/Button.module.scss
> +  color: $pureWhite;
Poprawiłem i ujednoliciłem.

2023-04-16 17:22 UTC, Evil-Cloud89 commented on src/styles/settings.scss
Obecne kolory to te co występowały na stronie we wszystkich komponentach. Nazwy nadałem by starać się odwzorować logiczność barwy. Plik przygotowałem tak by w przypadku zmiany kolorów z obecnie dostępnych będzie wystarczyło podmienić nazwę zmiennej przy w konkretnym miejscu na stornie oraz zawsze daje możliwość dodania nowego koloru (np. red jako kolor testowy).

2023-04-17 11:22 UTC, iMdPd approved these changes

2023-04-17 15:05 UTC, stanleyoos approved these changes

2023-04-17 15:53 UTC, matwjablonski commented
rozwiąż konflikty

2023-04-19 14:52 UTC, Evil-Cloud89 commented
Konflikty rozwiązane.

2023-04-20 13:29 UTC, merged